# Generated by Django 4.2.4 on 2024-05-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN',
            fields=[
                ('adminID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=20)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminpassword', models.CharField(max_length=15)),
                ('admin', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('studId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studName', models.CharField(max_length=20)),
                ('studEmail', models.EmailField(max_length=254)),
                ('studpassword', models.CharField(max_length=15)),
                ('studPhone', models.CharField(max_length=13)),
            ],
        ),
    ]
