# Generated by Django 4.2.4 on 2024-06-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPP_App', '0004_rename_adminpassword_admin_adminpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MPP',
        ),
    ]
