# Generated by Django 4.2.4 on 2024-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPP_App', '0006_mpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVITYASSIGN',
            fields=[
                ('activityassignname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activityassigndate', models.DateField()),
                ('activityassignwork', models.TextField()),
                ('activityassignmpp', models.TextField()),
                ('activityassigndate2', models.DateField()),
            ],
        ),
    ]
