# Generated by Django 4.2.4 on 2024-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPP_App', '0007_activityassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityassign',
            name='activityassignperkara',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
