# Generated by Django 4.2.4 on 2024-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPP_App', '0008_activityassign_activityassignperkara'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVITY',
            fields=[
                ('activityname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activitystartdate', models.DateField()),
                ('activityenddate', models.DateField()),
                ('activityperkara', models.TextField()),
                ('activityimage1', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('activityimage2', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('activityimage3', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
            ],
        ),
    ]
